### ISSUE TITLE
#Equipment How to balance keyboard ergonomics + quiet-ness

### ISSUE THREAD

**Issue by matthewpoer** [mikeal/self-care#7]
```
keyboardRequirements:
    # avoid carpel tunnel, wrist pain, etc
    - ergonomic
    # avoid irritating spouse cohabiting in small space
    - quiet
```

Looking for recommendations on keyboards. Can be wired or wireless, any price point I guess, so long as it keeps my wife happy and beats the 2018 Macbook Pro's keyboard in comfort/ergo.

I've been to Fry's and Best Buy and I've typed on a bunch. The [Microsoft Sculpt](https://www.microsoft.com/accessories/en-us/products/keyboards/sculpt-ergonomic-desktop/l5v-00001) is comfortable and might be the quietest I've tried, but it's still audible. Is there such a thing as a silent keyboard? If so I'm not finding it. There was a mechanical "pro gamer"-marketed keyboard that felt awesome to type on but it was so loud that it would have been mentioned in the divorce papers that it surely would have triggered.

I've been told I'm a violent typist.

**Comment by kergoth** [comment]
I think it depends a great deal on your preferences and requirements. https://www.amazon.com/dp/B06XSPGL9S/ with Cherry MX Browns, then install o-rings to dampen the impacts, would likely be a viable option. I'm happy with my semi-custom mechanical keyboard using Zealio's Zilent switches, but it's non-ergonomic, sadly. My keyboard with browns+o-rings is fairly quiet, though, just not as much as that one. There are other options if you care about how your switches feel and want to dive down the mechanical keyboard rabbithole.

**Comment by asgartech** [comment]
The Logitech K840 is pretty solid for $50. I use it in an open-plan office and have never had any complaints.

**Comment by matthewpoer** [comment]
Gotta come back to let the world know that I <3 the [Logitech K860](https://www.logitech.com/en-us/product/k860-split-ergonomic-keyboard) that came out in January 2020.

![image](https://user-images.githubusercontent.com/727257/80038956-a7afe380-84c4-11ea-8cbe-4563b4c3fd09.png)

It's quiet but has good feel, built-in KVM, works over bluetooth _and_ a tiny USB receiver. Works with Mac so well you might think it's an Apple product. Pairs perfectly with the [Logitech MX Vertical mouse](https://www.logitech.com/en-us/product/mx-vertical-ergonomic-mouse).
